export const COUNTRIES = [
  { code: "AF", name: "أفغانستان", nameEn: "Afghanistan" },
  { code: "AL", name: "ألبانيا", nameEn: "Albania" },
  { code: "DZ", name: "الجزائر", nameEn: "Algeria" },
  { code: "AD", name: "أندورا", nameEn: "Andorra" },
  { code: "AO", name: "أنغولا", nameEn: "Angola" },
  { code: "AG", name: "أنتيغوا وبربودا", nameEn: "Antigua and Barbuda" },
  { code: "AR", name: "الأرجنتين", nameEn: "Argentina" },
  { code: "AM", name: "أرمينيا", nameEn: "Armenia" },
  { code: "AU", name: "أستراليا", nameEn: "Australia" },
  { code: "AT", name: "النمسا", nameEn: "Austria" },
  { code: "AZ", name: "أذربيجان", nameEn: "Azerbaijan" },
  { code: "BS", name: "البهاما", nameEn: "Bahamas" },
  { code: "BH", name: "البحرين", nameEn: "Bahrain" },
  { code: "BD", name: "بنغلاديش", nameEn: "Bangladesh" },
  { code: "BB", name: "بربادوس", nameEn: "Barbados" },
  { code: "BY", name: "بيلاروسيا", nameEn: "Belarus" },
  { code: "BE", name: "بلجيكا", nameEn: "Belgium" },
  { code: "BZ", name: "بليز", nameEn: "Belize" },
  { code: "BJ", name: "بنين", nameEn: "Benin" },
  { code: "BT", name: "بوتان", nameEn: "Bhutan" },
  { code: "BO", name: "بوليفيا", nameEn: "Bolivia" },
  { code: "BA", name: "البوسنة والهرسك", nameEn: "Bosnia and Herzegovina" },
  { code: "BW", name: "بوتسوانا", nameEn: "Botswana" },
  { code: "BR", name: "البرازيل", nameEn: "Brazil" },
  { code: "BN", name: "بروناي", nameEn: "Brunei" },
  { code: "BG", name: "بلغاريا", nameEn: "Bulgaria" },
  { code: "BF", name: "بوركينا فاسو", nameEn: "Burkina Faso" },
  { code: "BI", name: "بوروندي", nameEn: "Burundi" },
  { code: "CV", name: "الرأس الأخضر", nameEn: "Cape Verde" },
  { code: "KH", name: "كمبوديا", nameEn: "Cambodia" },
  { code: "CM", name: "الكاميرون", nameEn: "Cameroon" },
  { code: "CA", name: "كندا", nameEn: "Canada" },
  { code: "CF", name: "جمهورية أفريقيا الوسطى", nameEn: "Central African Republic" },
  { code: "TD", name: "تشاد", nameEn: "Chad" },
  { code: "CL", name: "تشيلي", nameEn: "Chile" },
  { code: "CN", name: "الصين", nameEn: "China" },
  { code: "CO", name: "كولومبيا", nameEn: "Colombia" },
  { code: "KM", name: "جزر القمر", nameEn: "Comoros" },
  { code: "CG", name: "الكونغو", nameEn: "Congo" },
  { code: "CD", name: "جمهورية الكونغو الديمقراطية", nameEn: "Democratic Republic of Congo" },
  { code: "CR", name: "كوستاريكا", nameEn: "Costa Rica" },
  { code: "CI", name: "ساحل العاج", nameEn: "Ivory Coast" },
  { code: "HR", name: "كرواتيا", nameEn: "Croatia" },
  { code: "CU", name: "كوبا", nameEn: "Cuba" },
  { code: "CY", name: "قبرص", nameEn: "Cyprus" },
  { code: "CZ", name: "جمهورية التشيك", nameEn: "Czech Republic" },
  { code: "DK", name: "الدنمارك", nameEn: "Denmark" },
  { code: "DJ", name: "جيبوتي", nameEn: "Djibouti" },
  { code: "DM", name: "دومينيكا", nameEn: "Dominica" },
  { code: "DO", name: "جمهورية الدومينيكان", nameEn: "Dominican Republic" },
  { code: "EC", name: "الإكوادور", nameEn: "Ecuador" },
  { code: "EG", name: "مصر", nameEn: "Egypt" },
  { code: "SV", name: "السلفادور", nameEn: "El Salvador" },
  { code: "GQ", name: "غينيا الاستوائية", nameEn: "Equatorial Guinea" },
  { code: "ER", name: "إريتريا", nameEn: "Eritrea" },
  { code: "EE", name: "إستونيا", nameEn: "Estonia" },
  { code: "SZ", name: "إسواتيني", nameEn: "Eswatini" },
  { code: "ET", name: "إثيوبيا", nameEn: "Ethiopia" },
  { code: "FJ", name: "فيجي", nameEn: "Fiji" },
  { code: "FI", name: "فنلندا", nameEn: "Finland" },
  { code: "FR", name: "فرنسا", nameEn: "France" },
  { code: "GA", name: "الغابون", nameEn: "Gabon" },
  { code: "GM", name: "غامبيا", nameEn: "Gambia" },
  { code: "GE", name: "جورجيا", nameEn: "Georgia" },
  { code: "DE", name: "ألمانيا", nameEn: "Germany" },
  { code: "GH", name: "غانا", nameEn: "Ghana" },
  { code: "GR", name: "اليونان", nameEn: "Greece" },
  { code: "GD", name: "غرينادا", nameEn: "Grenada" },
  { code: "GT", name: "غواتيمالا", nameEn: "Guatemala" },
  { code: "GN", name: "غينيا", nameEn: "Guinea" },
  { code: "GW", name: "غينيا بيساو", nameEn: "Guinea-Bissau" },
  { code: "GY", name: "غيانا", nameEn: "Guyana" },
  { code: "HT", name: "هايتي", nameEn: "Haiti" },
  { code: "HN", name: "هندوراس", nameEn: "Honduras" },
  { code: "HU", name: "المجر", nameEn: "Hungary" },
  { code: "IS", name: "أيسلندا", nameEn: "Iceland" },
  { code: "IN", name: "الهند", nameEn: "India" },
  { code: "ID", name: "إندونيسيا", nameEn: "Indonesia" },
  { code: "IR", name: "إيران", nameEn: "Iran" },
  { code: "IQ", name: "العراق", nameEn: "Iraq" },
  { code: "IE", name: "أيرلندا", nameEn: "Ireland" },
  { code: "IL", name: "إسرائيل", nameEn: "Israel" },
  { code: "IT", name: "إيطاليا", nameEn: "Italy" },
  { code: "JM", name: "جامايكا", nameEn: "Jamaica" },
  { code: "JP", name: "اليابان", nameEn: "Japan" },
  { code: "JO", name: "الأردن", nameEn: "Jordan" },
  { code: "KZ", name: "كازاخستان", nameEn: "Kazakhstan" },
  { code: "KE", name: "كينيا", nameEn: "Kenya" },
  { code: "KI", name: "كيريباتي", nameEn: "Kiribati" },
  { code: "KP", name: "كوريا الشمالية", nameEn: "North Korea" },
  { code: "KR", name: "كوريا الجنوبية", nameEn: "South Korea" },
  { code: "KW", name: "الكويت", nameEn: "Kuwait" },
  { code: "KG", name: "قيرغيزستان", nameEn: "Kyrgyzstan" },
  { code: "LA", name: "لاوس", nameEn: "Laos" },
  { code: "LV", name: "لاتفيا", nameEn: "Latvia" },
  { code: "LB", name: "لبنان", nameEn: "Lebanon" },
  { code: "LS", name: "ليسوتو", nameEn: "Lesotho" },
  { code: "LR", name: "ليبيريا", nameEn: "Liberia" },
  { code: "LY", name: "ليبيا", nameEn: "Libya" },
  { code: "LI", name: "ليختنشتاين", nameEn: "Liechtenstein" },
  { code: "LT", name: "ليتوانيا", nameEn: "Lithuania" },
  { code: "LU", name: "لوكسمبورغ", nameEn: "Luxembourg" },
  { code: "MG", name: "مدغشقر", nameEn: "Madagascar" },
  { code: "MW", name: "ملاوي", nameEn: "Malawi" },
  { code: "MY", name: "ماليزيا", nameEn: "Malaysia" },
  { code: "MV", name: "جزر المالديف", nameEn: "Maldives" },
  { code: "ML", name: "مالي", nameEn: "Mali" },
  { code: "MT", name: "مالطا", nameEn: "Malta" },
  { code: "MH", name: "جزر مارشال", nameEn: "Marshall Islands" },
  { code: "MR", name: "موريتانيا", nameEn: "Mauritania" },
  { code: "MU", name: "موريشيوس", nameEn: "Mauritius" },
  { code: "MX", name: "المكسيك", nameEn: "Mexico" },
  { code: "FM", name: "ميكرونيزيا", nameEn: "Micronesia" },
  { code: "MD", name: "مولدوفا", nameEn: "Moldova" },
  { code: "MC", name: "موناكو", nameEn: "Monaco" },
  { code: "MN", name: "منغوليا", nameEn: "Mongolia" },
  { code: "ME", name: "الجبل الأسود", nameEn: "Montenegro" },
  { code: "MA", name: "المغرب", nameEn: "Morocco" },
  { code: "MZ", name: "موزمبيق", nameEn: "Mozambique" },
  { code: "MM", name: "ميانمار", nameEn: "Myanmar" },
  { code: "NA", name: "ناميبيا", nameEn: "Namibia" },
  { code: "NR", name: "ناورو", nameEn: "Nauru" },
  { code: "NP", name: "نيبال", nameEn: "Nepal" },
  { code: "NL", name: "هولندا", nameEn: "Netherlands" },
  { code: "NZ", name: "نيوزيلندا", nameEn: "New Zealand" },
  { code: "NI", name: "نيكاراغوا", nameEn: "Nicaragua" },
  { code: "NE", name: "النيجر", nameEn: "Niger" },
  { code: "NG", name: "نيجيريا", nameEn: "Nigeria" },
  { code: "MK", name: "مقدونيا الشمالية", nameEn: "North Macedonia" },
  { code: "NO", name: "النرويج", nameEn: "Norway" },
  { code: "OM", name: "عُمان", nameEn: "Oman" },
  { code: "PK", name: "باكستان", nameEn: "Pakistan" },
  { code: "PW", name: "بالاو", nameEn: "Palau" },
  { code: "PS", name: "فلسطين", nameEn: "Palestine" },
  { code: "PA", name: "بنما", nameEn: "Panama" },
  { code: "PG", name: "بابوا غينيا الجديدة", nameEn: "Papua New Guinea" },
  { code: "PY", name: "باراغواي", nameEn: "Paraguay" },
  { code: "PE", name: "بيرو", nameEn: "Peru" },
  { code: "PH", name: "الفلبين", nameEn: "Philippines" },
  { code: "PL", name: "بولندا", nameEn: "Poland" },
  { code: "PT", name: "البرتغال", nameEn: "Portugal" },
  { code: "QA", name: "قطر", nameEn: "Qatar" },
  { code: "RO", name: "رومانيا", nameEn: "Romania" },
  { code: "RU", name: "روسيا", nameEn: "Russia" },
  { code: "RW", name: "رواندا", nameEn: "Rwanda" },
  { code: "KN", name: "سانت كيتس ونيفيس", nameEn: "Saint Kitts and Nevis" },
  { code: "LC", name: "سانت لوسيا", nameEn: "Saint Lucia" },
  { code: "VC", name: "سانت فنسنت والغرينادين", nameEn: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "ساموا", nameEn: "Samoa" },
  { code: "SM", name: "سان مارينو", nameEn: "San Marino" },
  { code: "ST", name: "ساو تومي وبرينسيبي", nameEn: "Sao Tome and Principe" },
  { code: "SA", name: "السعودية", nameEn: "Saudi Arabia" },
  { code: "SN", name: "السنغال", nameEn: "Senegal" },
  { code: "RS", name: "صربيا", nameEn: "Serbia" },
  { code: "SC", name: "سيشل", nameEn: "Seychelles" },
  { code: "SL", name: "سيراليون", nameEn: "Sierra Leone" },
  { code: "SG", name: "سنغافورة", nameEn: "Singapore" },
  { code: "SK", name: "سلوفاكيا", nameEn: "Slovakia" },
  { code: "SI", name: "سلوفينيا", nameEn: "Slovenia" },
  { code: "SB", name: "جزر سليمان", nameEn: "Solomon Islands" },
  { code: "SO", name: "الصومال", nameEn: "Somalia" },
  { code: "ZA", name: "جنوب أفريقيا", nameEn: "South Africa" },
  { code: "SS", name: "جنوب السودان", nameEn: "South Sudan" },
  { code: "ES", name: "إسبانيا", nameEn: "Spain" },
  { code: "LK", name: "سريلانكا", nameEn: "Sri Lanka" },
  { code: "SD", name: "السودان", nameEn: "Sudan" },
  { code: "SR", name: "سورينام", nameEn: "Suriname" },
  { code: "SE", name: "السويد", nameEn: "Sweden" },
  { code: "CH", name: "سويسرا", nameEn: "Switzerland" },
  { code: "SY", name: "سوريا", nameEn: "Syria" },
  { code: "TW", name: "تايوان", nameEn: "Taiwan" },
  { code: "TJ", name: "طاجيكستان", nameEn: "Tajikistan" },
  { code: "TZ", name: "تنزانيا", nameEn: "Tanzania" },
  { code: "TH", name: "تايلاند", nameEn: "Thailand" },
  { code: "TL", name: "تيمور الشرقية", nameEn: "East Timor" },
  { code: "TG", name: "توغو", nameEn: "Togo" },
  { code: "TO", name: "تونغا", nameEn: "Tonga" },
  { code: "TT", name: "ترينيداد وتوباغو", nameEn: "Trinidad and Tobago" },
  { code: "TN", name: "تونس", nameEn: "Tunisia" },
  { code: "TR", name: "تركيا", nameEn: "Turkey" },
  { code: "TM", name: "تركمانستان", nameEn: "Turkmenistan" },
  { code: "TV", name: "توفالو", nameEn: "Tuvalu" },
  { code: "UG", name: "أوغندا", nameEn: "Uganda" },
  { code: "UA", name: "أوكرانيا", nameEn: "Ukraine" },
  { code: "AE", name: "الإمارات العربية المتحدة", nameEn: "United Arab Emirates" },
  { code: "GB", name: "المملكة المتحدة", nameEn: "United Kingdom" },
  { code: "US", name: "الولايات المتحدة", nameEn: "United States" },
  { code: "UY", name: "أوروغواي", nameEn: "Uruguay" },
  { code: "UZ", name: "أوزبكستان", nameEn: "Uzbekistan" },
  { code: "VU", name: "فانواتو", nameEn: "Vanuatu" },
  { code: "VA", name: "الفاتيكان", nameEn: "Vatican City" },
  { code: "VE", name: "فنزويلا", nameEn: "Venezuela" },
  { code: "VN", name: "فيتنام", nameEn: "Vietnam" },
  { code: "YE", name: "اليمن", nameEn: "Yemen" },
  { code: "ZM", name: "زامبيا", nameEn: "Zambia" },
  { code: "ZW", name: "زيمبابوي", nameEn: "Zimbabwe" }
];

export const getCountryName = (code: string): string => {
  const country = COUNTRIES.find(c => c.code === code);
  return country ? country.name : code;
};

export const getCountryNameEn = (code: string): string => {
  const country = COUNTRIES.find(c => c.code === code);
  return country ? country.nameEn : code;
};